### ISSUE TITLE
Change "Alberta Environment and Parks" to "Alberta Environment and Protected Areas"

### ISSUE THREAD

**Issue by nehill197** [poissonconsulting/bisonpictools#26]
```[tasklist]
### Tasks
- [x] Check the contributors
- [x] Check the license
- [x] Check the vignettes
- [x] Double check anything else using a find-all on "Alberta" in `bisonpictools`
- [x] Double check anything else using a find-all on "Alberta" in `shinybisonpic`
- [x] Double check anything else using a find-all on "Alberta" in `runbisonpic`
```
