### ISSUE TITLE
Address questions about the exploratory plots in the user guide

### ISSUE THREAD

**Issue by nehill197** [poissonconsulting/bisonpictools#27]
```[tasklist]
### Tasks
- [x] Add more detail to the user guide about the numerator:(numerator + denominator) ratio used in the plots.
- [x] Relay the additional detail to Troy via email.
- [x] Confirm whether or not Troy would like to add the ability to select a specific location/time in the ratio plots.
```
The questions are:
- These are ratios based on the full dataset from all cameras and dates, or can you select a specific location and/or time?
- I'm not sure what the (denominator + numerator) means here. For instance, a calf:cow ratio would be calves / cows, not calves / (cows+calves). 
- Does this mean you can select multiple types for either the numerator and denominator? Are those multiple groups then summed? I think that's what implied, just confirming.
